spring:
  datasource:
    hikari:
      password: pass
      username: java
      jdbc-url: jdbc:postgresql://localhost:5432/euphoria
    url: jdbc:postgresql://localhost:5432/euphoria
    password: pass
    username: java
  liquibase:
    change-log: db/changelog-master.xml
server:
  port: 8081