pipeline {
    agent {
        label 'agent1'
    }
    stages {
        stage('Start') {
            steps {
                sh 'echo START!!!!'
            }
        }
        stage('mvn clean install') {
            steps {
                sh 'mvn clean install'
            }
        }
        stage ('java - jar ') {
            steps {
                sh 'java -jar OPEN_PROECT-1.0-SNAPSHOT.jar'
            }
        }
    }
}